### ISSUE TITLE
Fails with compose

### ISSUE THREAD

**Issue by ronag** [progrium/docker-consul#88]
This works:

```
$(docker run --rm progrium/consul cmd:run 192.168.99.101::192.168.99.100::client -d) 
```

while this fails:

```
consul:
  image: progrium/consul
  command: -join 192.168.99.100
  ports:
  - "8300:8300"
  - "8301:8301"
  - "8301:8301/udp"
  - "8302:8302"
  - "8302:8302/udp"
  - "8400:8400"
  - "8500:8500"
  - "172.17.42.1:53:53"
  - "172.17.42.1:53:53/udp"
  volumes:
  - "/mnt:/data"
```

With:

```
memberlist: Refuting a suspect message (from: consul) 
```

Any ideas?
